Refactoring

diff --git a/img-tag-base64 b/img-tag-base64
--- a/img-tag-base64
+++ b/img-tag-base64
@@ -1,25 +1,40 @@
 #!/bin/bash
 
-if [ -z "$1" ]
+ARG_IMAGE_INPUT=$1;
+ARG_IMAGE_FORMAT=$2;
+
+DEFAULT_IMAGE_FOMRAT="jpeg";
+
+if [ -z "$ARG_IMAGE_INPUT" ]
   then
-    echo "No image path supplied"
-else
-
-  OUTPUT="<img src=\"data:image/jpeg;base64,$(base64 -w 0 $1)\">" 
-
-  echo "$OUTPUT"
-  if [ -x "$(command -v xclip)" ]
-    then
-      version="$(uname -a)"
-      if [[ $version == *"Microsoft"* ]]
-      then
-        echo -n "$OUTPUT" | clip.exe
-      else
-        echo -n "$OUTPUT" | xclip -selection clipboard
-      fi
-      echo ""
-      echo "img tag also copied to clipboard"
+    echo "ERROR! No input image path supplied";
+    echo "Usage examples:";
+    echo "img-tag-base64 image.png";
+    exit 1;
   else
-    echo "$OUTPUT"
-  fi
+    COMMAND_IMAGE_INPUT=$ARG_IMAGE_INPUT;
 fi
+
+if [ -z "$ARG_IMAGE_FORMAT" ]
+  then
+    COMMAND_IMAGE_FORMAT=$DEFAULT_IMAGE_FOMRAT;
+    echo "WARNING! No image format for base64 supplied. Default value set to: $COMMAND_IMAGE_FORMAT";
+  else
+    COMMAND_IMAGE_FORMAT=$ARG_IMAGE_FORMAT;
+fi
+
+echo "Image format output: $COMMAND_IMAGE_FORMAT";
+    
+OUTPUT="<img src=\"data:image/$COMMAND_IMAGE_FORMAT;base64,$(base64 -w 0 $COMMAND_IMAGE_INPUT)\">" 
+
+echo "$OUTPUT";
+
+if [ -x "$(command -v xclip)" ]
+  then
+    echo -n "$OUTPUT" | xclip -selection clipboard
+    echo ""
+    echo "HTML image tag also copied to clipboard"
+else
+  echo "$OUTPUT"
+fi
+
diff --git a/mp4-to-gif b/mp4-to-gif
--- a/mp4-to-gif
+++ b/mp4-to-gif
@@ -1,29 +1,49 @@
 #!/bin/bash
 
-OUTPUT_FILE_NAME="out.gif";
-FRAME_RATE=5;
+ARG_INPUT_VIDEO_FILE_NAME=$1;
+ARG_OUTPUT_GIF_FILE_NAME=$2;
+ARG_OUTPUT_FRAME_RATE=$3;
 
-if [ -z "$1" ]
-  then
-    echo "ERROR! No file video input supplied as 1st parameter.";
-    echo "Examples:";
-    echo "mp4-to-gif.sh video.mp4 video.gif";
-    echo "mp4-to-gif.sh video.mp4 video.gif 10";
-    exit 1;
-fi
+DEFAULT_OUTPUT_FILE_NAME="out.gif";
+DEFAULT_OUTPUT_FRAME_RATE=5;
 
-if [ -z "$2" ]
+if [ -x "$(command -v ffmpeg)" ]
   then
-    echo "WARNING! No output file name supplied as 2nd parameter. Default output name: $OUTPUT_FILE_NAME";
+  
+    if [ -z "$ARG_INPUT_VIDEO_FILE_NAME" ]
+      then
+        echo "ERROR! No file video input supplied as 1st parameter.";
+        echo "Usage examples:";
+        echo "mp4-to-gif.sh video.mp4 video.gif";
+        echo "mp4-to-gif.sh video.mp4 video.gif 10";
+        exit 1;
+      else
+        COMMAND_INPUT_VIDEO_FILE_NAME=$ARG_INPUT_VIDEO_FILE_NAME;
+    fi
+    
+    if [ -z "$ARG_OUTPUT_GIF_FILE_NAME" ]
+      then
+        COMMAND_OUTPUT_GIF_FILE_NAME=$DEFAULT_OUTPUT_FILE_NAME;
+        echo "WARNING! No output file name supplied as 2nd parameter. Default output name: $COMMAND_OUTPUT_GIF_FILE_NAME";
+      else
+        COMMAND_OUTPUT_GIF_FILE_NAME=$ARG_OUTPUT_GIF_FILE_NAME;
+    fi
+    
+    if [ -z "$ARG_OUTPUT_FRAME_RATE" ]
+      then
+        COMMAND_OUTPUT_FRAME_RATE=$DEFAULT_OUTPUT_FRAME_RATE;
+        echo "WARNING! No frame rate supplied as 3rd parameter. Value set to: $COMMAND_OUTPUT_FRAME_RATE";
+      else
+        COMMAND_OUTPUT_FRAME_RATE=$ARG_OUTPUT_FRAME_RATE;
+    fi
+    
+    # Execute video conversion to gif
+    ffmpeg -i $COMMAND_INPUT_VIDEO_FILE_NAME -r $COMMAND_OUTPUT_FRAME_RATE -pix_fmt rgb24 $COMMAND_OUTPUT_GIF_FILE_NAME
+    
   else
-    OUTPUT_FILE_NAME=$2;
+    echo "ERROR! ffmpeg must be installed and in PATH.";
 fi
 
-if [ -z "$3" ]
-  then
-    echo "WARNING! No frame rate supplied as 3rd parameter. Value set to: $FRAME_RATE";
-  else
-    FRAME_RATE=$3;
-fi
 
-ffmpeg -i $1 -r $FRAME_RATE -pix_fmt rgb24 $OUTPUT_FILE_NAME
+
+
